language: go
go_import_path: github.com/grokify/gotilla
go:
  - "1.14.x"
  - "1.13.x"
  - "1.12.x"
  - tip
matrix:
  allow_failures:
    - go: "1.12.x"
    - go: tip
sudo: true
install:
  - go get -t -v ./...
script:
  - go test -v ./...
